### ISSUE TITLE
About Biologically-Inspired-Visual-Odometry.

### ISSUE THREAD

**Issue by xlong0513** [weijia-yao/cdc20_singularity#1]
Hi, @weijia-yao , sorry to say that, but I have an issue in  [Biologically-Inspired-Visual-Odometry](https://github.com/nubot-nudt/Biologically-Inspired-Visual-Odometry/issues/1). And I found that you  first commit this repository. So can you solve the problem for me?

**Comment by weijia-yao** [comment]
Please contact Professor Huimin Lu at lhmnew@nudt.edu.cn.
